/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on Dec 1, 2011, 2:29:35 AM
 */
package addictionmanager.wizard;

import org.jdesktop.application.Action;

/**
 *
 * @author Deminem
 */
public class Step3 extends javax.swing.JPanel {

    /** Creates new form Step1 */
    public Step3() {
        initComponents();
        
        alertOption1.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alertOption1 = new javax.swing.JRadioButton();
        alertOption2 = new javax.swing.JRadioButton();
        alertOption3 = new javax.swing.JRadioButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(addictionmanager.AddictionManagerApp.class).getContext().getResourceMap(Step3.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 386));

        alertOption1.setText(resourceMap.getString("alertOption1.text")); // NOI18N
        alertOption1.setName("alertOption1"); // NOI18N
        alertOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertOption1ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(addictionmanager.AddictionManagerApp.class).getContext().getActionMap(Step3.class, this);
        alertOption2.setAction(actionMap.get("radioAction2")); // NOI18N
        alertOption2.setText(resourceMap.getString("alertOption2.text")); // NOI18N
        alertOption2.setName("alertOption2"); // NOI18N
        alertOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertOption2ActionPerformed(evt);
            }
        });

        alertOption3.setAction(actionMap.get("radioAction3")); // NOI18N
        alertOption3.setText(resourceMap.getString("alertOption3.text")); // NOI18N
        alertOption3.setName("alertOption3"); // NOI18N
        alertOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertOption3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(44, 44, 44)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(alertOption3)
                    .add(alertOption1)
                    .add(alertOption2))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(79, 79, 79)
                .add(alertOption1)
                .add(45, 45, 45)
                .add(alertOption2)
                .add(46, 46, 46)
                .add(alertOption3)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alertOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertOption2ActionPerformed
        
        if (alertOption2.isSelected()) {
            alertOption1.setSelected(false);
            alertOption3.setSelected(false);
        }
    }//GEN-LAST:event_alertOption2ActionPerformed

    private void alertOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertOption1ActionPerformed
        
        System.out.println("dddd");
        if (alertOption1.isSelected()) {
            alertOption2.setSelected(false);
            alertOption3.setSelected(false);
        }
    }//GEN-LAST:event_alertOption1ActionPerformed

    private void alertOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertOption3ActionPerformed
        
        if (alertOption3.isSelected()) {
            alertOption2.setSelected(false);
            alertOption1.setSelected(false);
        }
    }//GEN-LAST:event_alertOption3ActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton alertOption1;
    public javax.swing.JRadioButton alertOption2;
    public javax.swing.JRadioButton alertOption3;
    // End of variables declaration//GEN-END:variables
}
