/*
 * AddictionManagerView.java
 */

package addictionmanager;

import java.awt.Dimension;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class AddictionManagerView extends FrameView {

    public AddictionManagerView(SingleFrameApplication app) {
        super(app);

        initComponents();
        
        
        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = AddictionManagerApp.getApplication().getMainFrame();
            aboutBox = new AddictionManagerAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        AddictionManagerApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        mainPanel = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(addictionmanager.AddictionManagerApp.class).getContext().getResourceMap(AddictionManagerView.class);
        jDesktopPane1.setBackground(resourceMap.getColor("jDesktopPane1.background")); // NOI18N
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBounds(10, 20, 160, 100);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBackground(resourceMap.getColor("siderBarPanel.background")); // NOI18N
        jDesktopPane2.setName("siderBarPanel"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(10, 70, 50, 16);
        jDesktopPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(addictionmanager.AddictionManagerApp.class).getContext().getActionMap(AddictionManagerView.class, this);
        jButton2.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setToolTipText(resourceMap.getString("jButton2.toolTipText")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setSelected(true);
        jButton2.setSelectedIcon(resourceMap.getIcon("jButton2.selectedIcon")); // NOI18N
        jButton2.setBounds(0, 30, 180, 30);
        jDesktopPane2.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setBounds(10, 10, 70, 15);
        jDesktopPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton3.setIcon(resourceMap.getIcon("nextActivityBtn.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("nextActivityBtn.text")); // NOI18N
        jButton3.setToolTipText(resourceMap.getString("nextActivityBtn.toolTipText")); // NOI18N
        jButton3.setName("nextActivityBtn"); // NOI18N
        jButton3.setSelected(true);
        jButton3.setSelectedIcon(resourceMap.getIcon("nextActivityBtn.selectedIcon")); // NOI18N
        jButton3.setBounds(0, 120, 180, 30);
        jDesktopPane2.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton4.setIcon(resourceMap.getIcon("todayActivityBtn.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("todayActivityBtn.text")); // NOI18N
        jButton4.setToolTipText(resourceMap.getString("todayActivityBtn.toolTipText")); // NOI18N
        jButton4.setName("todayActivityBtn"); // NOI18N
        jButton4.setSelected(true);
        jButton4.setBounds(0, 90, 180, 30);
        jDesktopPane2.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton5.setIcon(resourceMap.getIcon("scheduleActivityBtn.icon")); // NOI18N
        jButton5.setText(resourceMap.getString("scheduleActivityBtn.text")); // NOI18N
        jButton5.setToolTipText(resourceMap.getString("scheduleActivityBtn.toolTipText")); // NOI18N
        jButton5.setName("scheduleActivityBtn"); // NOI18N
        jButton5.setSelected(true);
        jButton5.setSelectedIcon(resourceMap.getIcon("scheduleActivityBtn.selectedIcon")); // NOI18N
        jButton5.setBounds(0, 150, 180, 30);
        jDesktopPane2.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton6.setIcon(resourceMap.getIcon("somedayActivityBtn.icon")); // NOI18N
        jButton6.setText(resourceMap.getString("somedayActivityBtn.text")); // NOI18N
        jButton6.setToolTipText(resourceMap.getString("somedayActivityBtn.toolTipText")); // NOI18N
        jButton6.setName("somedayActivityBtn"); // NOI18N
        jButton6.setSelected(true);
        jButton6.setSelectedIcon(resourceMap.getIcon("somedayActivityBtn.selectedIcon")); // NOI18N
        jButton6.setBounds(0, 180, 180, 30);
        jDesktopPane2.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton7.setIcon(resourceMap.getIcon("logbookBtn.icon")); // NOI18N
        jButton7.setText(resourceMap.getString("logbookBtn.text")); // NOI18N
        jButton7.setToolTipText(resourceMap.getString("logbookBtn.toolTipText")); // NOI18N
        jButton7.setName("logbookBtn"); // NOI18N
        jButton7.setSelected(true);
        jButton7.setSelectedIcon(resourceMap.getIcon("logbookBtn.selectedIcon")); // NOI18N
        jButton7.setBounds(0, 440, 180, 30);
        jDesktopPane2.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setAction(actionMap.get("showAboutBox")); // NOI18N
        jButton8.setIcon(resourceMap.getIcon("trashBtn.icon")); // NOI18N
        jButton8.setText(resourceMap.getString("trashBtn.text")); // NOI18N
        jButton8.setToolTipText(resourceMap.getString("trashBtn.toolTipText")); // NOI18N
        jButton8.setName("trashBtn"); // NOI18N
        jButton8.setSelected(true);
        jButton8.setSelectedIcon(resourceMap.getIcon("trashBtn.selectedIcon")); // NOI18N
        jButton8.setBounds(0, 470, 180, 30);
        jDesktopPane2.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(resourceMap.getColor("centerPanel.background")); // NOI18N
        jPanel2.setName("centerPanel"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 845, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 509, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDesktopPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPane2)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBar.setBackground(resourceMap.getColor("menuBar.background")); // NOI18N
        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, menuBar, org.jdesktop.beansbinding.ELProperty.create("${background}"), menuBar, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        fileMenu.setBackground(resourceMap.getColor("fileMenu.background")); // NOI18N
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setBackground(resourceMap.getColor("helpMenu.background")); // NOI18N
        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
}
